version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database (use your Supabase credentials)
      - DATABASE_URL=${DATABASE_URL}

      # Google Maps
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

      # Cloudflare R2
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}

      # App config
      - ENV=development
      - DEBUG=true
      - CONFIDENCE_THRESHOLD=0.7

    volumes:
      # Mount code for hot reload in development
      - ./backend:/app

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL for local development
  # Uncomment if you want to run DB locally instead of Supabase
  # postgres:
  #   image: postgis/postgis:15-3.3
  #   environment:
  #     POSTGRES_DB: nyc_scan
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
